#! /usr/bin/env python

import sys

if len(sys.argv) < 3:
	sys.exit(1)

pkg = sys.argv[1]
name = sys.argv[2]
ifdef = "WOMBAT_%s_%s_HPP" % (pkg.upper(), name.upper())
hpp = "#ifndef %s\n#define %s\n\n#endif" % (ifdef, ifdef)
cpp = "#include \"%s.hpp\"\n" % name

open("%s/%s.hpp" % (pkg, name), "w").write(hpp)
open("%s/%s.cpp" % (pkg, name), "w").write(cpp)
